title: Off-Sec Note Book
description: A documentation of assessments and exploits
theme: just-the-docs
baseurl: "/off-sec-notes"
color_scheme: dark_scheme
favicon: favicon.ico

aux_links:
 # Template Repository: https://github.com/just-the-docs/just-the-docs-template
