title: Off-Sec Note Book
description: A documentation of assessments and exploits
theme: just-the-docs
baseurl: "/docs"
#url: https://google.com

aux_links:
 # Template Repository: https://github.com/just-the-docs/just-the-docs-template
