title: Testing Titel
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
baseurl: "/docs"
url: https://google.com

aux_links:
 # Template Repository: https://github.com/just-the-docs/just-the-docs-template
